### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by xperiandri** [hishamco/jsLogger#1]
Could you build a NuGet package to publish it at least on MyGet if it requires some testing.
I would try it.

**Comment by hishamco** [comment]
FYI I added this repo to demonstrate the `jsLogger` that I blogged about. I'm not sure if it's a suitable time to build a NuGet package because it's still a demo 😄 

At least for now you need to download or fork the repo to play with the stuff that I made, probably I will think about MyGet, frankly I didn't try yet 😄

**Comment by henkmollema** [comment]
I've took the liberty to create a NuGet package from this idea: https://github.com/webenablebv/Logging.JavaScript. You might find it useful. 😄

**Comment by hishamco** [comment]
Sorry @xperiandri I forgot to create a NuGet package
Thanks @henkmollema, I think it's time use the same idea in BLAZOR 😄

**Comment by henkmollema** [comment]
Yeah definitely! I might look into it when starting with Blazor development.

**Comment by hishamco** [comment]
I will schedule this for upcoming blog posts :)

**Comment by hishamco** [comment]
IMHO `jsLogger` is playing nicely with `Blazor`, this is the repo https://github.com/hishamco/Blazor-JavaScript-Logger that show the integration

@xperiandri I think I will close this and it is a good to create a NuGet package for other repo
